## 학습목표
 1. 수치해석 라이브러리인 numpy의 이해 및 사용
 2. 데이터 분석 라이브러이인 pandas의 이해 및 사용

## numpy
 - 파이썬의 대표적인 수치해석 라이브러리
 - 벡터, 행렬등의 최적화된 data structure와 다양한 연산 제공
 - 다른 많은 machine learnig, 혹은 data analysis 패키지들에서 많이 사용 됨

* **numpy 모듈**
  - 모듈 설치 
    - pip install numpy
  - 모듈 임포트
    - import numpy as np (관례적으로 np 사용)

In [1]:
import numpy as np
print(np.__version__)

1.13.1


* **ndarray**
 - numpy의 기본 타입
 - n dimentional array를 의미
 - vector, matrix를 표현
 - numpy.array([])로 생성

In [2]:
arr1 = np.array([1, 3, 4, 6]) # 1차원 벡터 생성
arr2 = np.array([[0, 1, 2], [2, 4, 6]]) # 2차원 행렬 생성

print(arr1, type(arr1))
print(arr2, type(arr2))

[1 3 4 6] <class 'numpy.ndarray'>
[[0 1 2]
 [2 4 6]] <class 'numpy.ndarray'>


In [3]:
pure_array = range(10)
np_array = np.array(pure_array)
np_array
np_array.shape

(10,)

* **arange**
 - 내장 함수 range()와 동일한 기능을 수행함
 - ndarray 반환

In [4]:
arr3 = np.arange(1, 11)
print(arr3, type(arr3))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


* **linspace**
 - start, end를 n-1개의 균일한 간격으로 분할

In [5]:
# 0 - 2의 범위를 5-1 등분 한다는 이야기
arr4 = np.linspace(0, 100, 4)
print(arr4)

[   0.           33.33333333   66.66666667  100.        ]


* **zeros**
 - 전달된 tuple 사이즈 행렬 반환
 - 0으로 채워짐

In [6]:
print(np.zeros((2, 4)))
print(np.zeros(4))

print(np.zeros((2, 2, 2)))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[ 0.  0.  0.  0.]
[[[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]]


* **ones**
 - 전달된 tuple 사이즈 행렬 반환
 - 1로 채워짐

In [7]:
print(np.ones((3, 3, 2, 7, 8)))
#print np.ones(3)

[[[[[ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    ..., 
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]]

   [[ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    ..., 
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]]]


  [[[ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    ..., 
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]]

   [[ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    ..., 
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]]]


  [[[ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
   

* **random sub package**
  - 다양한 확률 분포를 이용한 랜덤 숫자로 채워진 ndarray 혹은 단일 값을 생성할 때 주로 사용

In [8]:
print(np.random.rand(3)) # [0, 1) 사이 출력
print(np.random.randn(3)) # 정규분포 여기서 n은 normal distribution ---> 정규분포이기 때문에 여기서 음수가 포함됨

[ 0.81415548  0.86976957  0.55640314]
[ 0.31982329  1.4188862  -1.84210263]


In [17]:
a = np.random.rand(3, 2)         # 3x2
a

array([[ 0.71648562,  0.25426587],
       [ 0.7793598 ,  0.95620102],
       [ 0.86667365,  0.68798166]])

In [15]:
a = np.random.rand(3, 2, 2)     #랜덤으로 2X2 3개
a

array([[[ 0.71842539,  0.15509625],
        [ 0.11532013,  0.52339994]],

       [[ 0.21151633,  0.70017432],
        [ 0.76832193,  0.17893919]],

       [[ 0.44317248,  0.89543536],
        [ 0.06685829,  0.17788217]]])

In [12]:
print(a)

0.8917759193327458


* ** seed ** 
 - 실험, 분석 등을 할 때, 랜덤 값 생성 시, 해당 값을 추후에 또 사용해야 할 경우가 필요
 - 해당 경우에는 seed함수를 미리 호출하여 랜덤한 값을 동일 한 값으로 유지 할 수 있음
 - seed() 함수 호출 시, 정수를 전달

In [29]:
np.random.seed(100)       #seed를 붙여주면 랜덤한 값이 한번 나온 후에는 고정돼서 바뀌지 않음
print(np.random.rand(2, 3))

[[ 0.54340494  0.27836939  0.42451759]
 [ 0.84477613  0.00471886  0.12156912]]


In [30]:
np.random.rand()
np.random.randint(1, 101, 10)

array([15, 35, 25, 16, 61, 59, 17, 10, 94, 87])

In [31]:
np.random.seed(0) # 랜덤한 값을 계속 유지하고 싶을 때 사용              // 괄호 안의 값은 별로 중요치 않음
print(np.random.rand())

np.random.seed(2) # 랜덤한 값을 계속 유지하고 싶을 때 사용
print(np.random.rand())

0.5488135039273248
0.43599490214200376


* **slicing**
 - 리스트, 문자열 slicing과 동일함
 - 단, ndarray의 차원이 높을 경우에는, 각 차원별로 slicing, indexing 가능

In [32]:
arr1 = np.array([1, 3, 4, 6])
arr2 = np.array([[0, 1, 3], [2, 4, 6], [3, 7, 8]])

In [33]:
print(arr1[0])
print(arr1[1:-1])

1
[3 4]


In [34]:
arr2

array([[0, 1, 3],
       [2, 4, 6],
       [3, 7, 8]])

In [36]:
print(arr2[:, :1])   #2차원부터는 차원을 얘기할 때 :를 사용 // 뒤의 :1은 1번째 전까지 1열만 다 가져오라는 의미

[[0]
 [2]
 [3]]


In [38]:
print(arr2[:, 0])   # 앞에는 차원이 유지되는데,  뒤는 차원이 하나 빠져서 1차원 벡터가 되어버림.

[0 2 3]


In [40]:
print(arr2[1, 1:])
print(arr2[1, 0])

[4 6]
2


In [43]:
arr2 = np.array([[0, 1, 3], [2, 4, 6]])

print(arr2[0])
print()
print(arr2[0, 1])    # 이건 스칼라값
print()
print(arr2[1:, :2])
print()
print(arr2[:, 2])
print()
print(arr2[:, 1:])

[0 1 3]

1

[[2 4]]

[3 6]

[[1 3]
 [4 6]]


* **Boolean selection**
  - bool 리스트로 해당 값이 True인 조건만 필터링

In [44]:
arr = np.array([1, 2, 4, 8, 9, 6, 12, 13])
lst = [1, 2, 4, 8, 9, 6, 12, 13]

print(lst % 2 == 0)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [45]:
arr = np.array([1, 2, 4, 8, 9, 6, 12, 13])
lst = [1, 2, 4, 8, 9, 6, 12, 13]

print(arr % 2 == 0)

[False  True  True  True False  True  True False]


In [48]:
even_mask = (arr % 2 == 0)
print(arr[even_mask])              # even_mask 라는 boolean 중에서 True인 것만 출력

print(arr[arr % 2 == 0])

#print(arr[[True, False, True, False]])

# 개수가 맞지 않아도 가능은 함 (warning)
#print(arr[[True, False]]) 


#위에 지운 것들은 python2에서 되던 것. python3에서는 안됨

[ 2  4  8  6 12]
[ 2  4  8  6 12]


In [49]:
arr[arr > 7]        # not and or의 순서는 같음
# & - AND 
# | - OR 
# ! - NOT 

array([ 8,  9, 12, 13])

In [51]:
arr[(arr > 7) | (arr<=5)]
# & - AND 
# | - OR 
# ! - NOT 

array([ 1,  2,  4,  8,  9, 12, 13])

* **ndarray operations**
  - scala와의 연산은 전체 원소에 대해 적용
  - 다른 ndarray와의 연산은 element-wise로 적용

In [52]:
arr = np.arange(1, 7) * 5
print(arr)

[ 5 10 15 20 25 30]


In [53]:
arr2 = arr ** 4
print(arr2)
print(arr2 ** 0.5)

[   625  10000  50625 160000 390625 810000]
[  25.  100.  225.  400.  625.  900.]


In [54]:
arr1 = np.arange(0, 30, 3) + 3
arr2 = np.arange(1, 11)
print(arr1, arr2)

print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 * arr1)
#print arr1 ^2 
print(arr1 ** 2)

[ 3  6  9 12 15 18 21 24 27 30] [ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[  3  12  27  48  75 108 147 192 243 300]
[  9  36  81 144 225 324 441 576 729 900]
[  9  36  81 144 225 324 441 576 729 900]


In [55]:
arr1 = np.array([[1, 1], [1, 1]])
arr2 = np.array([[2, 2], [2, 2]])

print(arr1 * arr2)  # 원소끼리의 곱
print(arr1.dot(arr2)) # 행렬 곱

[[2 2]
 [2 2]]
[[4 4]
 [4 4]]


* **logical operator**
  - all()
    - 모든 원소가 조건을 만족 시키면 True, 아니면 False
  - any()
    - 어떤 원소라도 조건을 만족 시키면 True, 아니면 False

In [56]:
arr = np.random.randint(1, 10, size = (4,4))
print(arr)

[[9 7 3 9]
 [8 3 2 6]
 [5 5 6 8]
 [4 7 5 4]]


In [58]:
print(np.all(arr < 7))          #all을 사용하면 한번에 체크할 수 있음.

False


In [60]:
print(np.any(arr == 9))    #any는 하나라도 가능하면 True

True


In [61]:
a = np.array([[2], [1]])
b = np.array([[3, 5]])

np.dot(a, b)

array([[ 6, 10],
       [ 3,  5]])

* **[2] ravel**
  - 다차원배열을 1차원으로 변경  (평평하게 펴는 것)

In [76]:
arr = np.array([np.arange(1, 6), np.arange(10, 15)])
print(arr)

[[ 1  2  3  4  5]
 [10 11 12 13 14]]


In [77]:
print(arr.ravel())

[ 1  2  3  4  5 10 11 12 13 14]


* **[3] flatten**
 - 다차원 배열을 1차원으로 변경
 - copy를 생성하여 변경함                (메모리를 공유하여 펴는 것)

In [72]:
print(arr.flatten())

[ 1  2  3  4  5 10 11 12 13 14]


In [73]:
print(arr.flatten('F')) # column을 우선으로 변경

[ 1 10  2 11  3 12  4 13  5 14]


In [78]:
# ravel vs flatten
f_arr = arr.flatten() # copy를 반환
r_arr = arr.ravel() # 원본 ndarray와 메모리 공유

r_arr[0] = 60

print(f_arr)
print(r_arr)
print(arr)

[ 1  2  3  4  5 10 11 12 13 14]
[60  2  3  4  5 10 11 12 13 14]
[[60  2  3  4  5]
 [10 11 12 13 14]]


* **[1] reshaping**
 - array의 shape을 재정렬
 - 이때, 서로의 전체 원소 개수가 맞아야 가능
 - 데이터 정제에 가장 많이 사용
   e.g) 이미지의 경우, 2차원 픽셀로 표현되나, 이것을 ml library로 전달하기 위해 reshape하여 사용

In [2]:
arr = np.arange(1, 16)
print(arr)
arr2 = arr.reshape(3, 5)
print(arr2)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


* **자주 쓰는 numpy 함수**

In [8]:
print(arr)
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.maximum(arr, np.array([99, 1, 2, 3, 4, 5, 6, 7, 8, 20, 30, 40, 50, 60, 70])))
print(np.std(arr))                               # 표준편차
print(np.argmin(arr))                         # 최소값의 인덱스
print(np.argmax(arr))
print(np.sum(arr))
print(np.sqrt(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1
8.0
8.0
15
[99  2  3  4  5  6  7  8  9 20 30 40 50 60 70]
4.32049379894
0
14
120
[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766  3.31662479  3.46410162
  3.60555128  3.74165739  3.87298335]


* **axis**
 - 몇몇 함수에는 axis keyword 파라미터가 존재
 - axis값이 없는 경우에는 전체 데이터에 대해 적용
 - axis값이 있는 경우에는, 해당 axis를 **따라서** 연산 적용

In [81]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr2))

21


In [82]:
# 1차원 적용
arr2 = np.array([1, 2, 3])
print(np.sum(arr2, axis=0))

6


In [83]:
# 1차원 적용
arr2 = np.array([1, 2, 3])
print(np.sum(arr2, axis=1))       #1을 하면 열이 1개밖에 없으므로 죽게된다.

AxisError: axis 1 is out of bounds for array of dimension 1

In [84]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [86]:
# 2차원 적용                               # 행이 0, 열이 1.

print(np.sum(arr2, axis=0))        # 행을 따라서 합하는 것
print(np.sum(arr2, axis=1))        # 열을 따라서 합하는 것

[5 7 9]
[ 6 15]


In [88]:
# 3차원 적용
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 1, 1], [2, 2, 2]]] )       #2X3이 2개
print(np.sum(arr2, axis=0))                          #0인 경우는 1 4, 2 5, 3 6과 같이 합하는 것.
print(np.sum(arr2, axis=1))                          #1인 경우는 열끼리 더함
print(np.sum(arr2, axis=2))                         #2인 경우는 제일 가운데를 기준으로 양 옆을 더함

[[2 3 4]
 [6 7 8]]
[[5 7 9]
 [3 3 3]]
[[ 6 15]
 [ 3  6]]


 * **numpy broadcasting**
  - 연산시, 차원이 맞지 않은 경우, 적은 차원의 ndarray를 상위 차원으로 broadcast하여 연산 진행

In [89]:
arr = np.arange(10)                #1차원 벡터
arr2 = np.arange(2, 12)          #1차원 벡터
arr3 = np.arange(10).reshape(2, 5)

arr + arr2 # 기본적으로 element-wise 연산

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [90]:
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
2 ** arr 

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [92]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [93]:
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
arr3 + arr[1:6]

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14]])

* **연습문제**
1. numpy를 이용하여 Math.pi 값을 다시 구해봅시다.
2. python 기본 리스트 객체로 만든 두 행렬을 곱하는 코드를 작성하시오.

In [3]:
trial = int(1e8)
p_sum = np.sum(np.random.rand(trial, 2) ** 2, axis = 1)
4.0 * np.sum(p_sum < 1) / trial

3.1417291600000001

* **linear regression 실습**

* generate random data

In [ ]:
x = np.random.randn(100)
x.shape, x

In [ ]:
y = 4 * x + 30 + 1.1 * np.random.randn(100)
y.shape, y

* plot data 

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline 

In [ ]:
plt.scatter(x, y, c='r', marker='o')

* create a model

In [ ]:
x = x.reshape(100, 1)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x, y)

* check coefficient, bias(intercept)

In [ ]:
w = model.coef_
b = model.intercept_

w, b

* plot data with our model

In [ ]:
plt.scatter(x, y, c='r', marker='o')
plt.plot(x, w * x + b, 'g-')

* **pandas**
  - http://pandas.pydata.org/
  - Opensource python 고성능 데이터 분석 라이브러리
  - DataFrame, Series 객체가 가장 많이 사용
  - ML library인 scikit-learn과 함께 ML 분석에 많이 사용 됨
  - pip install pandas로 설치
  - 관례적으로 pd 로 임포트

In [ ]:
import numpy as np
import pandas as pd

 * **Series**
  - pandas의 기본 객체 중 하나
  - numpy의 ndarray를 기반으로 인덱싱을 기능을 추가하여 1차원 배열을 나타냄
  - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성
  - 같은 타입의 0개 이상의 데이터를 가질 수 있음

In [ ]:
s1 = pd.Series([1, 2,  20])
print(s1)

In [ ]:
print(s1[0])

In [ ]:
s2 = pd.Series(list(range(1, 6)))
print(s2)

 * **값 및 인덱스 접근**
  - 각가 values, index 속성

In [ ]:
print(s2.values)

In [ ]:
print(s2.index)

* **index 지정하기**

In [ ]:
print(chr(97))
print([chr(i) for i in range(97, 100)])

In [ ]:
print(chr(97))

s3 = pd.Series(list(range(1, 4)), index = [chr(i) for i in range(97, 100)])
print(s3)
print()
print(s3.values)
print()
print(s3.index)

In [ ]:
print(s3[1]) # 기본 인덱스
print(s3['c']) 

* **index 재사용**

In [ ]:
s4 = pd.Series(2, index = s3.index)
print(s4)

In [ ]:
s5 = pd.Series(np.random.randn(5))
print(s5)

In [ ]:
s6 = pd.Series(np.arange(1, 9))
print(s6)

In [ ]:
s7 = pd.Series({'a' : 100, 'b' : 1000, 'c' : 2, 'd' : 6})
print(s7)
print(s7['b'])

* **Series size, shape, unique, count, value_counts**
 - size : 개수 반환
 - shape : 튜플형태로 shape반환
 - unique: 유일한 값만 ndarray로 반환
 - count : NaN을 제외한 개수를 반환
 - value_counts: NaN을 제외하고 각 값들의 빈도를 반환 

In [ ]:
s = pd.Series([0, 1, 1, 2, 3, 4, 5, 6, 7, np.nan])
print(s)

In [ ]:
print(len(s))

In [ ]:
print(s.size)

In [ ]:
print(s.shape)

In [ ]:
print(s.count()) # NaN을 제외한 값을 카운팅

In [ ]:
print(s.unique())

In [ ]:
print(s.value_counts()) # NaN 제외하고 값들을 카운팅 함

* **head, tail, take**
 - head : 상위 n개 출력 기본 5개
 - tail : 하위 n개 출력 기본 5개
 - take : 주어진 인덱스 리스트와 매칭되는 원소만 추출

In [ ]:
s.head() # 상위 5개 출력

In [ ]:
s.head(n = 3)

In [ ]:
s.tail()

In [ ]:
s.tail(n = 2)

In [ ]:
print(s)
print() 
print(s.take([0, 4, 3, 9]))

In [ ]:
s = pd.Series(np.arange(1, 4), index = ['x', 'y', 'z'])
s.take([0, 2])
#s.take(['x', 'z']) #0 - based index만 가능

 * **single value accessing**
  - 인덱스를 이용하여 값 접근 가능
  - 문자열 인덱스가 주어진 경우, 0-based index도 사용 가능
  

In [ ]:
print(s['x']) # 인덱스로 가능

In [ ]:
print(s[1]) # 숫자 인덱스도 가능

In [ ]:
s = pd.Series(np.arange(1, 4), index = [100, 101, 102])
print(s[100])
print(s[0]) # 에러

* **multiple values accessing**
 - 인덱스 리스트, ndarray로 여러 값에 접근 가능

In [ ]:
print(s)
print(s[[100, 102]])

* **loc , iloc**
  - loc[] : index로 값 접근
  - iloc[] : 0 based index로 값 접근

In [ ]:
print(s)

In [ ]:
print(s.loc[100])

In [ ]:
print(s.iloc[0])

In [ ]:
print(s.loc[[100, 102]])

In [ ]:
print(s.iloc[[0, 2]])

In [ ]:
s.loc[[100, 102, 104, 105]]

In [ ]:
# 에러 발생
# 인덱스 4가 없기 때문
s.iloc[[0, 2, 1, 4]] 

* **index를 기준으로 더하기**

In [ ]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
print(s1)

In [ ]:
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])
s2

In [ ]:
print(s1 + s2)

In [ ]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])
a1 + a2

* **산술연산**
 - Series의 경우에도 스칼라와의 연산은 각 원소별로 스칼라와의 연산이 적용
 - Series와의 연산은 각 인덱스에 맞는 값끼리 연산이 적용
   - 이때, 인덱스의 pair가 맞지 않으면, 결과는 NaN 

In [ ]:
print(s1)

In [ ]:
print(s1 ** 2)
print(s1)

In [ ]:
exp = pd.Series(2, s1.index)
print(s1 ** exp)

In [ ]:
s1 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 5})
s2 = pd.Series({'b': 6, 'c': 7, 'd': 9, 'e': 10})

print(s1 + s2)

 * **NaN (Not a Number)**
  - numpy와 비교

In [ ]:
nda = np.array([1, 2, 3, 4, 5])
nda.mean()
np.mean(nda)

In [ ]:
nda = np.array([1, 2, 3, 4, np.NaN])
nda.mean()

In [ ]:
s = pd.Series([1, 2, 3, 4, np.NaN])
print(s.mean())
print(s.mean(skipna=False))

 * **Boolean selection**
  - boolean Series가 []와 함께 사용되면 True 값에 해당하는 값만 새로 반환되는 Series객체에 포함됨

In [ ]:
s = pd.Series(np.arange(1, 10))
s > 5
print(s[s > 5])

In [ ]:
my_logic = s > 5
print(s[my_logic])

In [ ]:
print(s[s > 5])


In [ ]:
#print s > 5 and s < 8
#print s[s > 5 and s < 8]
print(s[(s > 5) & (s < 8)]) # & and , | or

In [ ]:
print((s >= 0).all())
print((s >= 2).all())

In [ ]:
print((s < 2).any())
print(s[s < 2].any())

In [ ]:
print(s)
print() 
print(s[s >= 7].sum())
print((s >= 7).sum())

* **Series 값 변경**
  - 인덱스를 이용하여 변경  


In [ ]:
s = pd.Series([1, 10, 100], index = ['a', 'b', 'c'])
s['d'] = 1000

print(s)

s['d'] = 10000
print(s)

In [ ]:
del s['a']
print(s)

* **Slicing**
 - 리스트, ndarray와 동일하게 적용

In [ ]:
s.value_counts()

In [ ]:
s = pd.Series(np.arange(100, 110), index=np.arange(10, 20))
print(s)
print(s[0:5])
print(s[:5])
print(s[5:])
print(s[-3:])

* **DataFrame**
  - Series가 1차원이라면 DataFrame은 2차원으로 확대된 버젼
  - Excel spreadsheet이라고 생각하면 이해하기 쉬움
  - 2차원이기 때문에 인덱스가 row, column로 구성됨

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame(np.array([[10, 11], [20, 22]]))
print(df)

In [ ]:
df = pd.DataFrame(np.array([2, 1, 2, 3]))
print(df, type(df))

* **shape**
 - row, column에 대한 튜플 값으로 볼 수 있음

In [ ]:
df1 = pd.DataFrame([pd.Series(np.arange(10, 15)) ,
            pd.Series(np.arange(20, 25))])
print(df1)
print(df1.shape)
print() 
print(df1.info())
print() 
print(df1.describe())

In [ ]:
df = pd.DataFrame(np.array([[10, 20], [20, 30]]), 
                  columns = ['a', 'b'])
print(df)
print(df.columns)
print(df.columns[0], df.columns[1])

df.columns = ['t1', 't2']
print(df)

In [ ]:
df = pd.DataFrame(np.array([[10, 20], [20, 30]]), 
                  columns = ['a', 'b'], index = ['d1', 'd2'])
print(df)
print(df.index)

* **Series dictionary로 부터 생성**

In [ ]:
s1 = pd.Series(np.arange(1, 6, 1))
s2 = pd.Series(np.arange(6, 11, 1))
df = pd.DataFrame({'c1': s1, 'c2': s2})

print(df)

* **csv 데이터로 부터 dataframe 생성**
  - dataframe을 생성하는 가장 보편적인 방법
  - 데이터 소스로부터 추출된 csv(comma separated values) 파일로 부터 df 생성

In [2]:
import numpy as np
import pandas as pd

In [8]:
sample_df = pd.read_csv('sample.csv')
sample_df.head(n=3)

Symbol                 Name       Sector   Price  Dividend Yield  \
0    MMM           3M Company  Industrials  177.12            2.53   
1    ABT  Abbott Laboratories  Health Care   41.89            2.55   
2   ABBV               AbbVie  Health Care   64.16            3.60   

   Price/Earnings  Earnings/Share  Book Value  52 week low  52 week high  \
0           22.77            7.78       19.34       134.00        177.79   
1           25.79            1.62       14.10        36.00         51.74   
2           19.29            3.33        2.87        45.45         71.60   

   Market Cap  EBITDA  Price/Sales  Price/Book  \
0      107.43    8.57         3.52        9.04   
1       61.54    4.40         2.98        2.93   
2      103.77   10.30         4.31       22.09   

                                         SEC Filings  
0  http://www.sec.gov/cgi-bin/browse-edgar?action...  
1  http://www.sec.gov/cgi-bin/browse-edgar?action...  
2  http://www.sec.gov/cgi-bin/browse-edgar?action...

In [10]:
sample_df = pd.read_csv('sample.csv', usecols = [0, 1, 2, 3, 7])
sample_df.head()

Symbol                 Name                  Sector   Price  Book Value
0    MMM           3M Company             Industrials  177.12       19.34
1    ABT  Abbott Laboratories             Health Care   41.89       14.10
2   ABBV               AbbVie             Health Care   64.16        2.87
3    ACN        Accenture plc  Information Technology  115.11       11.45
4   ATVI  Activision Blizzard  Information Technology   41.29       11.31

In [5]:
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', usecols = [0, 1, 2, 3, 7])
sample_df.head()

Name                  Sector   Price  Book Value
Symbol                                                                 
MMM              3M Company             Industrials  177.12       19.34
ABT     Abbott Laboratories             Health Care   41.89       14.10
ABBV                 AbbVie             Health Care   64.16        2.87
ACN           Accenture plc  Information Technology  115.11       11.45
ATVI    Activision Blizzard  Information Technology   41.29       11.31

In [6]:
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', 
                        usecols=['Name', 'Symbol', 'Price'])
sample_df.head()

Name   Price
Symbol                             
MMM              3M Company  177.12
ABT     Abbott Laboratories   41.89
ABBV                 AbbVie   64.16
ACN           Accenture plc  115.11
ATVI    Activision Blizzard   41.29

* **data 개수**

In [ ]:
print(len(sample_df))

In [ ]:
print(sample_df.index)
print() 
print(sample_df.columns)

* **dataframe slicing**
  - dataframe의 경우 기본적으로 [] 연산자가 column 선택에 사용
  - 따라서 [0], ['some val'] 과 같이 하면 column 레벨의 데이터 추출
  - 하지만, 유일하게 slicing은 row 레벨로 지원

In [ ]:
print(pd.__version__)

In [ ]:
#apple_df = pd.read_csv('apple.csv', header = None)
apple_df = pd.read_csv('apple.csv')
#print apple_df[:10]
apple_df.head()

In [ ]:
print(apple_df['High'])

* **column 선택하기**
  - df에서 특정 컬럼의 데이터만 추출
  - 컬럼 이름일 경우 이름만 사용 가능
  - 컬럼 인덱스일 경우 인덱스의 리스트 사용 가능

In [ ]:
# 숫자 인덱스로 컬럼 셀렉션 확인 할 것 
apple_df[['Date', 'Close', 'Volume']] # 인덱스로도 가능

In [ ]:
print(type(apple_df[[0, 4, 5]]))
print(type(apple_df[[0]]))
print(type(apple_df[['Date']]))
print(type(apple_df[['Date', 'Close']]))
print(type(apple_df['Date']))

In [ ]:
print(apple_df.Date)
print(apple_df.Close)

* **row 선택하기**
  - Seires의 경우 []로 row 선택이 가능하나, **DataFrame의 경우는 기본적으로 column을 선택하도록 설계**
  - [:10]과 같이 slicing의 경우에는 row 선택 가능
  - .loc, .iloc, .ix 의 함수로 row 선택 가능

In [ ]:
print(apple_df[0:10])

print(apple_df.loc[0])


In [ ]:
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', 
                        usecols = [0, 1, 2, 3, 7])
sample_df

In [ ]:
print(sample_df.loc['MMM'])

In [ ]:
print(sample_df.loc[['MMM', 'MSFT']])

In [ ]:
print(sample_df.iloc[[0, 1, 2]])
print(type(sample_df.iloc[[0, 1, 2]]))

print(sample_df.iloc[0]) 
print(type(sample_df.iloc[0]))

* **ix**
 - iloc, loc 구별없이 사용하고 싶을 때 사용

In [ ]:
print(sample_df.ix[['MSFT', 'ZTS']])

In [ ]:
print(sample_df.ix[[10, 11, 12, 15]])

* **boolean selection으로 row 선택하기**

In [ ]:
print(sample_df.Price > 100)
print(sample_df['Price'] > 100)

In [ ]:
sample_df[sample_df['Price'] > 100][['Name', 'Price']]

In [ ]:
print(sample_df[sample_df.Price > 100][['Price']])

In [ ]:
sample_df.head()

* **새 column 추가하기**

In [ ]:
# 새로운 dataframe 생성
copy = sample_df.copy()

# 새로 생성된 프레임에 새로운 컬럼 추가 (기존 컬럼 이용)
copy['TwicePrice'] = sample_df.Price * 2
copy.head()

In [ ]:
copy['ratio'] = copy['Price'] / copy['Book Value']
copy.head()

In [ ]:
# insert 함수를 이용하여 원하는 컬럼 위치에 삽입 가능
copy.insert(1, 'TriplePrice', sample_df.Price * 3)
copy.head()

 * **column 삭제하기**

In [ ]:
print(copy[:2])

# del 키워드로 삭제
del copy['TriplePrice']
print(copy[:2])

 * **row 추가/삭제하기**

In [ ]:
df1 = copy.iloc[0:3].copy()
print(df1)

# append 함수 사용
copy = copy.append(df1)
print(copy.tail())



In [ ]:
# 인덱스가 유일 값을 가져야 하는데???
copy.loc['MMM']

In [ ]:
# drop 함수를 사용하여 해당 row 제거
copy = copy.drop(['ABBV'])
copy.tail()